In [33]:
import numpy as np
import pandas as pd

import re
import time

from sklearn.metrics import pairwise_distances

In [51]:
anon_data = pd.read_csv('anon_data/ring_mondrian/k1_minmaxed.csv')
anon_data.rename(columns={"Unnamed: 0":"index"}, inplace=True)
anon_data.set_index("index")

,A0_min,A0_max,A1_min,A1_max,A2_min,A2_max,A3_min,A3_max,A4_min,A4_max,...,A15_max,A16_min,A16_max,A17_min,A17_max,A18_min,A18_max,A19_min,A19_max,class
index,,,,,,,,,,,,,,,,,,,,,
0,849,849,2177,2177,598,598,1689,1689,3114,3114,...,-166,578,578,1664,1664,309,309,-3028,-3028,0
1,947,947,543,543,782,782,-449,-449,-8,-8,...,1008,2687,2687,-1422,-1422,-606,-606,2374,2374,1
2,759,759,-314,-314,898,898,-1743,-1743,2003,2003,...,1431,-336,-336,79,79,1123,1123,302,302,1
3,531,531,1374,1374,517,517,1226,1226,1122,1122,...,1216,916,916,-476,-476,6,6,-477,-477,1
4,-1443,-1443,1065,1065,2071,2071,207,207,-865,-865,...,4097,1356,1356,-944,-944,-602,-602,2348,2348,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7395,607,607,1539,1539,139,139,1378,1378,-2178,-2178,...,-413,136,136,-509,-509,1423,1423,1142,1142,1
7396,-122,-122,-1654,-1654,-395,-395,278,278,-193,-193,...,-5735,173,173,1505,1505,-1098,-1098,-5196,-5196,0
7397,-1854,-1854,1225,1225,-2469,-2469,-351,-351,1193,1193,...,1051,-2244,-2244,2871,2871,-3462,-3462,1619,1619,0
7398,2604,2604,-1541,-1541,1298,1298,-742,-742,-238,-238,...,157,602,602,606,606,573,573,-751,-751,1
7399,-239,-239,472,472,2795,2795,-1672,-1672,-802,-802,...,-277,-3445,-3445,-2969,-2969,-132,-132,3362,3362,0

In [52]:
cols = list(anon_data.columns[1:-1])

def distance(u,v):
    u = u[cols]
    v = v[cols]
    d = u == v
    counts = d.value_counts()
    return counts[False] if False in counts else 0

In [53]:
def diam_m(data):
    data = data[cols]
    data = data.drop_duplicates()
    diam = 0
    for x in range(len(data)):
        for y in range(x+1, len(data)):
            
            d = distance(data.iloc[x], data.iloc[y])
            
            if d == len(cols):
                print(f"max distance is {d}")
                return d
            
            if d > diam:
                diam = d
                
    return diam

#diam_m(anon_data)

In [54]:
rel_cols = anon_data[cols]

In [59]:
dists = pairwise_distances(rel_cols, metric="hamming")

In [60]:
print(dists)

[[0. 1. 1. ... 1. 1. 1.]
 [1. 0. 1. ... 1. 1. 1.]
 [1. 1. 0. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 1. 1.]
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 1. 1. 0.]]

In [61]:
max_dist = 0

for x in range(len(dists[0])):
    r_max = max(dists[x])
    if r_max > max_dist:
        max_dist = r_max
    if max_dist == 1:
        break
        
print(max_dist)

1.0